# Generated by Django 5.2.8 on 2025-11-27 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('crotaliu', models.CharField(blank=True, max_length=50, null=True)),
                ('data_nastere', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('sanatate', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'animale',
            },
        ),
        migrations.CreateModel(
            name='Parcele',
            fields=[
                ('id_parcela', models.AutoField(primary_key=True, serialize=False)),
                ('suprafata', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('locatie', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'parcele',
            },
        ),
        migrations.CreateModel(
            name='Resurse',
            fields=[
                ('id_resursa', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(blank=True, max_length=100, null=True)),
                ('cantitate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'resurse',
            },
        ),
        migrations.CreateModel(
            name='Specii',
            fields=[
                ('id_specie', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'specii',
            },
        ),
        migrations.CreateModel(
            name='Utilizatori',
            fields=[
                ('id_utilizator', models.AutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('parola', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('cnp', models.CharField(blank=True, db_column='CNP', max_length=13, null=True, unique=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('stare_cont', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'utilizatori',
            },
        ),
        migrations.CreateModel(
            name='Insamantari',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('data_ins', models.DateField(blank=True, null=True)),
                ('data_est', models.DateField(blank=True, null=True)),
                ('data_fatare', models.DateField(blank=True, null=True)),
                ('id_animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='ferma.animale')),
            ],
            options={
                'db_table': 'insamantari',
            },
        ),
        migrations.CreateModel(
            name='Culturi',
            fields=[
                ('id_cultura', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('cantitate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_parcela', models.ForeignKey(db_column='id_parcela', on_delete=django.db.models.deletion.DO_NOTHING, to='ferma.parcele')),
            ],
            options={
                'db_table': 'culturi',
            },
        ),
        migrations.AddField(
            model_name='animale',
            name='id_specie',
            field=models.ForeignKey(db_column='id_specie', on_delete=django.db.models.deletion.DO_NOTHING, to='ferma.specii'),
        ),
        migrations.CreateModel(
            name='Tratamente',
            fields=[
                ('id_tratament', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('medicament', models.CharField(blank=True, max_length=100, null=True)),
                ('id_animal', models.ForeignKey(db_column='id_animal', on_delete=django.db.models.deletion.DO_NOTHING, to='ferma.animale')),
            ],
            options={
                'db_table': 'tratamente',
            },
        ),
        migrations.CreateModel(
            name='Rapoarte',
            fields=[
                ('id_raport', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('start_per', models.DateField(blank=True, null=True)),
                ('stop_per', models.DateField(blank=True, null=True)),
                ('id_utilizator', models.ForeignKey(db_column='id_utilizator', on_delete=django.db.models.deletion.DO_NOTHING, to='ferma.utilizatori')),
            ],
            options={
                'db_table': 'rapoarte',
            },
        ),
    ]
